'use client';
import dynamic from 'next/dynamic';
import {useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {Bot,CheckCircle2,Code2,Play,Timer,Trophy,RotateCcw,Send,BarChart3,GitBranch} from 'lucide-react';
const Editor=dynamic(()=>import('@monaco-editor/react'),{ssr:false});
const qs=[['Detect a Cycle in a Linked List','Data Structures & Algorithms','Medium'],['Longest Substring Without Repeating Characters','Strings','Medium'],['Design a Rate Limiter','System Design Basics','Hard'],['Number of Islands','Graphs','Medium'],['Project Architecture Deep Dive','Project Based','Medium'],['Lowest Common Ancestor','Trees','Medium'],['Dynamic Programming Trade-off','Algorithms','Hard'],['Microservices Failure Handling','System Design','Hard']];
const starter={Python:`class Solution:\n    def hasCycle(self, head):\n        slow = fast = head\n        while fast and fast.next:\n            slow = slow.next\n            fast = fast.next.next\n            if slow == fast:\n                return True\n        return False`,JavaScript:`function hasCycle(head) {\n  let slow=head, fast=head;\n  while(fast && fast.next){ slow=slow.next; fast=fast.next.next; if(slow===fast)return true; }\n  return false;\n}`};
const wait=(n:number)=>new Promise(r=>setTimeout(r,n));
export default function Page(){
 const p=useParams<{slug?:string[]}>(),r=useRouter(),page=p.slug?.join('/')||'';
 const [role,setRole]=useState('Software Engineer'),[lang,setLang]=useState('Python'),[difficulty,setDifficulty]=useState('Medium'),[count,setCount]=useState(8),[i,setI]=useState(0),[code,setCode]=useState(starter.Python),[running,setRunning]=useState(false),[submitted,setSubmitted]=useState(false),[score,setScore]=useState(88),[history,setHistory]=useState<string[]>([]),[elapsed,setElapsed]=useState(0);
 useEffect(()=>{const x=setInterval(()=>setElapsed(v=>v+1),1000);return()=>clearInterval(x)},[]);
 const nav=(x:string)=>r.push('/app/module3'+(x?'/'+x:'')); const q=qs[i%qs.length]; const run=async()=>{setRunning(true);await wait(900);setRunning(false)}; const submit=async()=>{setRunning(true);await wait(1100);setRunning(false);setSubmitted(true);setScore(86+(i%4))}; const next=()=>{if(i+1>=count){setHistory(h=>[...h,`${new Date().toLocaleDateString()} · ${role} · ${score}/100`]);nav('report')}else{setI(v=>v+1);setSubmitted(false);setCode(starter[lang as keyof typeof starter]||starter.Python)}};
 if(page==='setup')return <Shell nav={nav}><div className="card"><small>MODULE 3 · CONFIGURE</small><h1>Build your technical interview</h1><div className="form">{[['Role',role,setRole,['Frontend Developer','Backend Developer','Full Stack Developer','Software Engineer','Data Engineer','ML Engineer']],['Language',lang,setLang,['Python','JavaScript']],['Difficulty',difficulty,setDifficulty,['Easy','Medium','Hard']]].map(([a,v,set,opts])=><label key={String(a)}>{a}<select value={String(v)} onChange={e=>(set as (v:string)=>void)(e.target.value)}>{(opts as string[]).map(o=><option key={o}>{o}</option>)}</select></label>)}</div><label>Questions<select value={count} onChange={e=>setCount(+e.target.value)}><option>5</option><option>8</option><option>10</option></select></label><p className="notice">Demo Mode · Mock AI Interviewer · Simulated Evaluation · Local Demo Execution</p><button onClick={()=>nav('instructions')} className="primary">Continue <Play size={15}/></button></div></Shell>;
 if(page==='instructions')return <Shell nav={nav}><div className="card"><small>BEFORE YOU BEGIN</small><h1>Technical interview instructions</h1><div className="stats"><b>Role<span>{role}</span></b><b>Difficulty<span>{difficulty}</span></b><b>Language<span>{lang}</span></b><b>Questions<span>{count}</span></b></div><h3>Evaluation criteria</h3><div className="chips">{['Correctness','Code Quality','Efficiency','Problem Solving','Complexity','Communication','Edge Cases'].map(x=><span key={x}>{x}</span>)}</div><p className="notice">This is a simulated technical interview. AI evaluation and code execution are simulated locally.</p><button onClick={()=>nav('interview')} className="primary">Begin Interview <Play size={15}/></button></div></Shell>;
 if(page==='history')return <Shell nav={nav}><div className="card"><small>MODULE 3</small><h1>Interview History</h1>{history.length?history.map((x,j)=><div className="row" key={j}><span>{x}</span><button onClick={()=>nav('setup')}>Retry</button></div>):<div className="empty"><Trophy/><h2>No interview history yet.</h2><button className="primary" onClick={()=>nav('setup')}>Start Your First Interview</button></div>}</div></Shell>;
 if(page==='report'||page==='results')return <Shell nav={nav}><div className="report"><div className="score"><small>TECHNICAL SCORE</small><strong>{score}/100</strong><span>Excellent Performance</span></div><div className="grid2"><section className="card"><h2>Performance Analytics</h2>{[['Correctness',90],['Code Quality',86],['Efficiency',85],['Problem Solving',90],['Communication',90]].map(([x,v])=><div className="metric" key={String(x)}><span>{x}</span><b>{v}%</b><i><em style={{width:`${v}%`}}/></i></div>)}</section><section className="card"><h2>Complexity Analysis</h2><div className="complex"><b>O(n)<span>Time</span></b><b>O(1)<span>Space</span></b></div><p className="good"><CheckCircle2/> Optimal Solution</p><h2>Test Case Analysis</h2><p>10 passed · 1 failed · 1 edge case · 0 skipped</p></section><section className="card"><h2>Code Quality Analysis</h2><p>★★★★★ Readable Code</p><p>★★★★☆ Variable Naming</p><p>★★★★★ Function Decomposition</p><p>★★★★☆ Modularity</p><p>★★★★★ Maintainability</p></section><section className="card"><h2>Strengths</h2>{['Good problem understanding','Efficient approach','Handles edge cases','Clean and readable code','Strong DSA fundamentals'].map(x=><p className="good" key={x}><CheckCircle2/> {x}</p>)}</section><section className="card"><h2>Improvement Areas</h2>{['Optimize space in some cases','Improve code modularity','Practice more DP patterns','Improve complexity optimization'].map(x=><p className="warn" key={x}>⚠ {x}</p>)}</section><section className="card"><h2>Recommendations</h2><p>✓ Practice more Graph problems</p><p>✓ Focus on DP & Greedy patterns</p><p>✓ Revise System Design basics</p><h2>Personalized Learning Roadmap</h2><p>Advanced DSA → System Design → Mock Interviews</p></section></div><button className="primary" onClick={()=>nav('setup')}>Start Next Mock Interview</button></div></Shell>;
 if(page==='interview'||page==='interview/coding'||page==='interview/evaluation')return <Shell nav={nav}><div className="head"><div><b><span className="live"/> AI Interviewer Online</b><small>{role} · {q[2]} · {q[1]}</small></div><span><Timer size={14}/> {String(Math.floor(elapsed/60)).padStart(2,'0')}:{String(elapsed%60).padStart(2,'0')} · Question {i+1}/{count}</span></div><div className="work"><section className="card"><small>TECHNICAL QUESTION · {q[2]}</small><h2>{q[0]}</h2><p>Given the problem above, explain your approach, complexity and edge cases before coding.</p><div className="notice">AI follow-up: Can you explain your approach before you start coding?</div></section><section className="card"><h3><Bot size={16}/> AI INTERVIEWER</h3><div className="chat"><p><b>AI:</b> Can you explain your approach before you start coding?</p><p><b>AI:</b> What happens when the input contains only one node?</p><p><b>AI:</b> Can you optimize the space complexity?</p></div><textarea placeholder="Type your explanation…"/><button>Submit explanation <Send size={14}/></button></section><section className="card editor"><div className="editorbar"><span><Code2 size={15}/> LIVE CODING INTERFACE</span><select value={lang} onChange={e=>{setLang(e.target.value);setCode(starter[e.target.value as keyof typeof starter]||starter.Python)}}><option>Python</option><option>JavaScript</option></select></div><Editor height="380px" language={lang==='Python'?'python':'javascript'} theme="vs-dark" value={code} onChange={v=>setCode(v||'')} options={{minimap:{enabled:false},fontSize:14,automaticLayout:true}}/><div className="buttons"><button onClick={()=>setCode(starter[lang as keyof typeof starter]||starter.Python)}><RotateCcw size={14}/> Reset</button><button onClick={run} disabled={running}><Play size={14}/> {running?'Running…':'Run Code'}</button><button className="primary" onClick={submit} disabled={running}><Send size={14}/> {running?'Evaluating…':'Submit'}</button></div><div className="console">{running?'Executing test cases…':'Execution completed.'}<br/>Execution Time: 18 ms · Memory: 24 MB · Tests Passed: {submitted?10:4}</div></section><section className="card"><h3>TEST CASES</h3>{[1,2,3,4,5].map(n=><div className="test" key={n}><span>{n<5||submitted?<CheckCircle2/>:'○'} Test Case {n}</span><small>{n<5||submitted?'Passed':'Pending'}</small></div>)}{submitted&&<p className="good"><CheckCircle2/> All test cases passed successfully! (simulated)</p>}</section></div><div className="follow"><span>Dynamic Follow-up Questions</span><b>{submitted?'What trade-off would you make if memory were constrained?':'Submit a solution to trigger contextual follow-up questions.'}</b><button onClick={next}>{i+1>=count?'Finish':'Continue'} →</button></div></Shell>;
 return <Shell nav={nav}><div className="hero"><div><small>MODULE 3</small><h1>AI Technical Interview Simulator</h1><p>Real Interviews. Real Questions. Real Feedback.</p><div className="buttons"><button className="primary" onClick={()=>nav('setup')}><Play size={15}/> Start Technical Interview</button><button onClick={()=>nav('setup')}>Try Demo Interview</button></div></div><div className="orb"><Bot size={54}/><b>AI Interviewer<br/>● Online</b></div></div><div className="features">{[['Real Technical Interviews',Code2],['AI Coding Evaluation',Bot],['Performance Analytics',BarChart3],['Personalized Roadmap',GitBranch]].map(([x,I])=>{const Icon=I as typeof Code2;return <div className="card" key={String(x)}><Icon/><h3>{x}</h3><p>Production-style interview workflow with deterministic mock services.</p><small>Demo Mode</small></div>})}</div><div className="card"><h2>What is Module 3?</h2><p>Module 3 simulates realistic technical interviews covering coding, DSA, system design, project reasoning and technical communication.</p><p>Workflow: AI Interviewer → Question → Explanation → Live Coding → Tests → Submission → Evaluation → Follow-up → Report → Roadmap.</p></div></Shell>;
}
function Shell({children,nav}:{children:React.ReactNode;nav:(x:string)=>void}){return <div className="m3"><header><button onClick={()=>nav('')} className="brand">✦ INTELLIHIRE</button><span>MODULE 3 · AI TECHNICAL INTERVIEW</span><nav><button onClick={()=>nav('')}>Module 3</button><button onClick={()=>nav('history')}>History</button><button onClick={()=>nav('settings')}>Settings</button></nav></header><main>{children}</main></div>}
