'use client';
import dynamic from 'next/dynamic';
import {useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {Bot,Code2,Play,Send,RotateCcw,CheckCircle2} from 'lucide-react';
const Editor=dynamic(()=>import('@monaco-editor/react'),{ssr:false});
const starter={Python:`def solve(nums):\n    # implement the solution\n    return nums`,JavaScript:`function solve(nums) {\n  // implement the solution\n  return nums;\n}`};
export default function Page(){
 const p=useParams<{slug?:string[]}>(),r=useRouter(),page=p.slug?.join('/')||'';
 const [role,setRole]=useState('Software Engineer'),[lang,setLang]=useState('Python'),[session,setSession]=useState<any>(null),[question,setQuestion]=useState<any>(null),[code,setCode]=useState(starter.Python),[answer,setAnswer]=useState(''),[result,setResult]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const api=async(path:string,options:RequestInit={})=>{const res=await fetch('/api/module3'+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Request failed');return data};
 useEffect(()=>{api('/resume').then(data=>{if(data.session&&!data.session.completed){setSession(data.session);setQuestion(data.question);r.push('/app/module3/interview')}}).catch(()=>{})},[]);
 const start=async()=>{setLoading(true);setError('');try{const data=await api('/start',{method:'POST',body:JSON.stringify({role})});setSession(data.session);setQuestion(data.question);r.push('/app/module3/interview')}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const evaluate=async()=>{if(!session)return;setLoading(true);setError('');try{const data=await api('/code/evaluate',{method:'POST',body:JSON.stringify({session_id:session.id,language:lang,code,question:question?.prompt||''})});setResult(data)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const submitAnswer=async()=>{if(!session||!answer.trim())return;setLoading(true);try{const data=await api('/answer',{method:'POST',body:JSON.stringify({session_id:session.id,answer})});setResult(data.evaluation);setAnswer('');setQuestion(data.next)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const finish=async()=>{if(!session)return;setLoading(true);try{const data=await api('/finish',{method:'POST',body:JSON.stringify({session_id:session.id})});setResult(data);r.push('/app/module3/results')}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 if(page==='setup'||!page)return <Shell nav={x=>r.push('/app/module3'+(x?'/'+x:''))}><div className="card"><small>MODULE 3 · PRODUCTION</small><h1>AI Technical Interview</h1><p>Persistent interview sessions with grounded AI code evaluation.</p><label>Target role<select value={role} onChange={e=>setRole(e.target.value)}><option>Software Engineer</option><option>Frontend Developer</option><option>Backend Developer</option><option>Data Engineer</option><option>ML Engineer</option></select></label><label>Language<select value={lang} onChange={e=>{setLang(e.target.value);setCode(starter[e.target.value as keyof typeof starter])}}><option>Python</option><option>JavaScript</option></select></label>{error&&<p className="error">{error}</p>}<button className="primary" onClick={start} disabled={loading}>{loading?'Starting…':'Start Interview'} <Play size={15}/></button></div></Shell>;
 if(page==='results')return <Shell nav={x=>r.push('/app/module3'+(x?'/'+x:''))}><div className="card"><small>MODULE 3 · RESULT</small><h1>Technical Evaluation</h1><div className="score">{result?.score ?? '—'}/100</div><p>{result?.questions_answered||0} questions answered.</p><button className="primary" onClick={()=>r.push('/app/module3/setup')}>Start another interview</button></div></Shell>;
 if(page==='interview')return <Shell nav={x=>r.push('/app/module3'+(x?'/'+x:''))}><div className="head"><div><b><span className="live"/> AI Interviewer Online</b><small>{session?.role}</small></div><span>Question {session?.progress+1}/{session?.total}</span></div><div className="work"><section className="card"><small>TECHNICAL QUESTION</small><h2>{question?.prompt||'Use the coding evaluator below.'}</h2><p>Explain your approach and submit your answer before evaluating the code.</p><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Explain your approach, complexity and edge cases…"/><button onClick={submitAnswer} disabled={loading||!answer.trim()}><Send size={14}/> Submit explanation</button></section><section className="card editor"><div className="editorbar"><span><Code2 size={15}/> SECURE STATIC EVALUATION</span><select value={lang} onChange={e=>{setLang(e.target.value);setCode(starter[e.target.value as keyof typeof starter])}}><option>Python</option><option>JavaScript</option></select></div><Editor height="380px" language={lang==='Python'?'python':'javascript'} theme="vs-dark" value={code} onChange={v=>setCode(v||'')} options={{minimap:{enabled:false},fontSize:14,automaticLayout:true}}/><div className="buttons"><button onClick={()=>setCode(starter[lang as keyof typeof starter])}><RotateCcw size={14}/> Reset</button><button className="primary" onClick={evaluate} disabled={loading}><Bot size={14}/> {loading?'Evaluating…':'Evaluate Code'}</button></div>{result&&<div className="console"><b>Score: {result.score}/100</b><br/>Correctness {result.correctness}% · Quality {result.code_quality}% · Security {result.security}% · Performance {result.performance}%<br/>{result.feedback}<br/>{(result.findings||[]).map((x:string,i:number)=><span key={i}>• {x}<br/></span>)}<small>Execution: {result.execution}. This evaluator does not execute candidate code.</small></div>}</section></div>{error&&<p className="error">{error}</p>}<div className="follow"><span>Persistent session</span><b>Progress is saved automatically.</b><button onClick={finish} disabled={loading}>Finish Interview →</button></div></Shell>;
 return <Shell nav={x=>r.push('/app/module3'+(x?'/'+x:''))}><div className="card"><h1>Module 3</h1><p>Production technical interview.</p><button className="primary" onClick={()=>r.push('/app/module3/setup')}>Start</button></div></Shell>;
}
function Shell({children,nav}:{children:React.ReactNode;nav:(x:string)=>void}){return <div className="m3"><header><button onClick={()=>nav('')} className="brand">✦ INTELLIHIRE</button><span>MODULE 3 · AI TECHNICAL INTERVIEW</span><nav><button onClick={()=>nav('')}>Module 3</button><button onClick={()=>nav('setup')}>New Interview</button></nav></header><main>{children}</main></div>}
