// This file is auto-generated by GitHub Actions
// DO NOT commit API keys to the repository
const ANTHROPIC_API_KEY = 'y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';

// API Configuration
const API_CONFIG = {
  baseURL: 'https://api.anthropic.com/v1/messages',
  model: 'claude-sonnet-4-20250514',
  maxTokens: 4096
};

// Helper function for API calls
async function callClaude(messages, systemPrompt = '') {
  const response = await fetch(API_CONFIG.baseURL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01'
    },
    body: JSON.stringify({
      model: API_CONFIG.model,
      max_tokens: API_CONFIG.maxTokens,
      system: systemPrompt,
      messages: messages
    })
  });
  
  if (!response.ok) {
    throw new Error(`API Error: ${response.status}`);
  }
  
  return await response.json();
}
