'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import AppShell from '../AppShell';

type Q={id:string;prompt:string;options:string[]};
type A={id:string;status:string;progress:number;total:number;ability:number;answered_ids:string[]};
export default function Module2Page(){
 const [assessment,setAssessment]=useState<A|null>(null),[q,setQ]=useState<Q|null>(null),[choice,setChoice]=useState<number|null>(null),[result,setResult]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const start=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/module2/assessments',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({target_questions:8})});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to start');setAssessment(d);const n=await fetch(`/api/module2/assessments/${d.id}/next`,{credentials:'include'});const nd=await n.json();setQ(nd.question)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const answer=async()=>{if(choice===null||!assessment||!q)return;setLoading(true);try{const r=await fetch(`/api/module2/assessments/${assessment.id}/answer`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({question_id:q.id,answer:choice})});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to save answer');setAssessment(d.assessment);setResult(d.result);setChoice(null);if(d.assessment.status==='COMPLETED'){setQ(null)}else{const n=await fetch(`/api/module2/assessments/${assessment.id}/next`,{credentials:'include'});const nd=await n.json();setQ(nd.question)}}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{fetch('/api/module2/assessments/latest',{credentials:'include'}).then(r=>r.ok?r.json():null).then(async d=>{if(d?.assessment?.status==='ACTIVE'){setAssessment(d.assessment);const n=await fetch(`/api/module2/assessments/${d.assessment.id}/next`,{credentials:'include'});const nd=await n.json();if(n.ok)setQ(nd.question)}}).catch(()=>{})},[]);
 return <AppShell><div className="card"><small>MODULE 2 · ADAPTIVE ASSESSMENT</small><h1>Adaptive Assessment</h1><p>Questions adapt to your demonstrated ability and persist progress between sessions.</p>{!assessment&&!loading&&<button className="primary" onClick={start}>Start Assessment →</button>}{loading&&!q&&<p>Loading assessment…</p>}{error&&<div className="notice">{error}</div>}{q&&assessment&&<><div className="notice">Question {assessment.progress+1} of {assessment.total}</div><h2>{q.prompt}</h2><div className="chips" style={{display:'grid'}}>{q.options.map((x,i)=><button key={x} className={choice===i?'primary':''} onClick={()=>setChoice(i)}>{x}</button>)}</div><button className="primary" onClick={answer} disabled={choice===null||loading}>{loading?'Saving…':'Submit answer'}</button></>}{result&&<div className="card"><small>CURRENT SCORE</small><h2>{result.score ?? result.overall ?? 0}/100</h2><p>Ability: {assessment?.ability ?? 0}</p>{assessment?.status==='COMPLETED'&&<Link href="/app/dashboard">Return to dashboard →</Link>}</div>}</div></AppShell>;
}
