'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import AppShell from '../AppShell';

type Session={id:string;status:string;question_index:number;total_questions?:number;role?:string};
export default function Module4Page(){
 const [session,setSession]=useState<Session|null>(null),[question,setQuestion]=useState<any>(null),[answer,setAnswer]=useState(''),[result,setResult]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const start=async()=>{setLoading(true);try{const r=await fetch('/api/module4/start',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({role:'Software Engineer',duration:15})});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to start');setSession(d.session);setQuestion(d.question)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const submit=async()=>{if(!session||!answer.trim())return;setLoading(true);try{const r=await fetch('/api/module4/answer',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({session_id:session.id,answer})});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to save answer');setSession(d.session||session);setQuestion(d.next);setAnswer('')}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const finish=async()=>{if(!session)return;setLoading(true);try{const r=await fetch('/api/module4/finish',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({session_id:session.id})});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to finish');setResult(d);setQuestion(null)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{fetch('/api/module4/history',{credentials:'include'}).then(r=>r.ok?r.json():null).then(d=>{const last=d?.interviews?.find((x:any)=>x.status==='IN_PROGRESS');if(last){setSession(last);fetch(`/api/module4/question?session_id=${last.id}`,{credentials:'include'}).then(r=>r.json()).then(x=>setQuestion(x.question)).catch(()=>{})}}).catch(()=>{})},[]);
 return <AppShell><div className="card"><small>MODULE 4 · HR & BEHAVIORAL</small><h1>Behavioral Interview</h1><p>Practice structured behavioral answers and receive competency evidence based on what you actually submit.</p>{!session&&<button className="primary" onClick={start} disabled={loading}>{loading?'Starting…':'Start HR Interview →'}</button>}{error&&<div className="notice">{error}</div>}{question&&session&&<><div className="notice">Question {session.question_index+1} · {session.role||'Software Engineer'}</div><h2>{question.prompt||question.text||question.question}</h2><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Use a concrete situation, action and result…"/><div className="buttons"><button className="primary" onClick={submit} disabled={!answer.trim()||loading}>{loading?'Saving…':'Submit answer'}</button><button onClick={finish} disabled={loading}>Finish interview</button></div></>}{result&&<div className="card"><small>INTERVIEW RESULT</small><h2>{result.score ?? 0}/100</h2><p>{result.summary||result.feedback||'Your behavioral evidence has been saved.'}</p><Link href="/app/dashboard">Return to dashboard →</Link></div>}</div></AppShell>;
}
