'use client';
import {useState} from 'react';
import Link from 'next/link';
import AppShell from '../AppShell';

type Result={atsScore:number;overallMatch:number;skillsMatch:number;keywordMatch:number;semanticSimilarity:number;missingSkills:string[];shortlist:string};
export default function Module1Page(){
 const [resume,setResume]=useState(''),[job,setJob]=useState(''),[result,setResult]=useState<Result|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const analyze=async()=>{setError('');setResult(null);if(!resume.trim()||!job.trim()){setError('Paste both your resume and the target Job Description.');return}setLoading(true);try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({resume:{text:resume},job:{description:job}})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Analysis failed');setResult(data)}catch(e:any){setError(e.message||'Analysis failed')}finally{setLoading(false)}};
 return <AppShell><div className="card"><small>MODULE 1 · ATS & RESUME INTELLIGENCE</small><h1>Resume Intelligence</h1><p>Compare your resume with a target role, identify missing skills and get a deterministic ATS-oriented match report.</p><div className="grid2"><label>Resume<textarea value={resume} onChange={e=>setResume(e.target.value)} placeholder="Paste resume text…"/></label><label>Target Job Description<textarea value={job} onChange={e=>setJob(e.target.value)} placeholder="Paste the job description…"/></label></div>{error&&<div className="notice">{error}</div>}<div className="buttons"><button className="primary" onClick={analyze} disabled={loading}>{loading?'Analyzing…':'Analyze Resume →'}</button><Link href="/app/dashboard">Dashboard</Link></div></div>{result&&<div className="card"><small>ANALYSIS RESULT</small><div className="stats"><b>ATS<span>{result.atsScore}%</span></b><b>Overall<span>{result.overallMatch}%</span></b><b>Skills<span>{result.skillsMatch}%</span></b><b>Keywords<span>{result.keywordMatch}%</span></b></div><div className="notice">{result.shortlist} · Semantic similarity {result.semanticSimilarity}%</div><h2>Priority skill gaps</h2>{result.missingSkills.length?<div className="chips">{result.missingSkills.map(s=><span key={s}>{s}</span>)}</div>:<p>No required skills are currently missing from the supplied resume.</p>}<p className="muted">This score is preparation evidence, not an employment decision.</p></div>}</AppShell>;
}
